//PACKAGES ACTION TYPES
export const PACKAGES_FETCH_ALL = 'PACKAGES_FETCH_ALL';
export const PACKAGES_CREATE = 'PACKAGES_CREATE';
export const PACKAGES_UPDATE = 'PACKAGES_UPDATE';
export const PACKAGES_CLEAR = 'PACKAGES_CLEAR'

//USER ACTION TYPES
export const USER_AUTH = 'USER_AUTH';
export const USER_GET = 'USER_GET';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE = 'USER_UPDATE';

//ALERT ACTION TYPES
export const ALERT_CLOSE = 'ALERT_CLOSE';
export const ALERT_CHANGE = 'ALERT_CHANGE';

